import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

# =========================
# 0. 随机种子
# =========================
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device =", device)

# =========================
# 1. 准备有限个目标点
# =========================
# 这里我先构造一个“偏移的双峰目标分布”的有限样本，作为 demo。
# 你实际用时，把 target_points 换成你自己的 1D 样本点即可。
n_target = 512
choose_left = np.random.rand(n_target) < 0.5

target_points = np.where(
    choose_left,
    np.random.normal(loc=-2.0, scale=0.35, size=n_target),  # 左峰
    np.random.normal(loc= 2.5, scale=0.45, size=n_target),  # 右峰（有偏移）
).astype(np.float32)

target_points = torch.tensor(target_points, dtype=torch.float32).view(-1, 1).to(device)

# =========================
# 2. 小模型：学习速度场 v(x, t)
# =========================
class VelocityMLP(nn.Module):
    def __init__(self, hidden_dim=64):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(2, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, x, t):
        # x: [B, 1], t: [B, 1]
        inp = torch.cat([x, t], dim=-1)   # [B, 2]
        return self.net(inp)              # [B, 1]

model = VelocityMLP(hidden_dim=64).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=2e-3)

# =========================
# 3. 从有限目标点里采样
# =========================
def sample_target_batch(target_points, batch_size):
    idx = torch.randint(0, target_points.shape[0], (batch_size,), device=target_points.device)
    return target_points[idx]

# =========================
# 4. 经典 Flow Matching 训练
# =========================
# 路径:
#   x_t = (1-t)x0 + t x1
# 速度目标:
#   u_t = x1 - x0
#
# 每一步:
#   x0 ~ N(0,1)
#   x1 ~ empirical target
#   t ~ Uniform(0,1)
#   令 x_t = (1-t)x0 + t x1
#   拟合 v_theta(x_t,t) ≈ x1-x0

num_steps = 3000
batch_size = 256
loss_history = []

for step in range(num_steps):
    x0 = torch.randn(batch_size, 1, device=device)             # source
    x1 = sample_target_batch(target_points, batch_size)        # target empirical sample
    t = torch.rand(batch_size, 1, device=device)

    x_t = (1.0 - t) * x0 + t * x1
    u_t = x1 - x0

    pred_v = model(x_t, t)
    loss = ((pred_v - u_t) ** 2).mean()

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    loss_history.append(loss.item())

    if (step + 1) % 300 == 0:
        print(f"step {step+1:4d} | loss = {loss.item():.6f}")

# =========================
# 5. 用学到的流场做采样：解 ODE
#    dx/dt = v_theta(x,t)
# =========================
@torch.no_grad()
def euler_integrate(model, x_init, n_steps=100):
    x = x_init.clone()
    traj = [x.clone()]
    ts = torch.linspace(0.0, 1.0, n_steps + 1, device=x.device)
    dt = 1.0 / n_steps

    for i in range(n_steps):
        t = torch.full_like(x, ts[i])
        v = model(x, t)
        x = x + dt * v
        traj.append(x.clone())

    traj = torch.stack(traj, dim=0)  # [T+1, B, 1]
    return ts, traj

# 生成一批样本
n_gen = 5000
x0_gen = torch.randn(n_gen, 1, device=device)
ts, traj = euler_integrate(model, x0_gen, n_steps=100)
x_gen = traj[-1, :, 0].cpu().numpy()

# =========================
# 6. 可视化 1：训练损失
# =========================
plt.figure(figsize=(6, 4))
plt.plot(loss_history)
plt.xlabel("train step")
plt.ylabel("MSE loss")
plt.title("Flow Matching Training Loss")
plt.tight_layout()
plt.savefig("fm_loss.png", dpi=150)
plt.show()

# =========================
# 7. 可视化 2：源分布 / 目标分布 / 生成分布
# =========================
target_np = target_points[:, 0].cpu().numpy()
source_np = np.random.randn(n_gen)

xmin = min(source_np.min(), target_np.min(), x_gen.min()) - 0.8
xmax = max(source_np.max(), target_np.max(), x_gen.max()) + 0.8
bins = np.linspace(xmin, xmax, 120)

plt.figure(figsize=(7, 4.5))
plt.hist(source_np, bins=bins, density=True, alpha=0.4, label="source N(0,1)")
plt.hist(target_np, bins=bins, density=True, alpha=0.4, label="target empirical")
plt.hist(x_gen, bins=bins, density=True, alpha=0.4, label="generated by learned flow")
plt.xlabel("x")
plt.ylabel("density")
plt.title("Distribution Matching Result")
plt.legend()
plt.tight_layout()
plt.savefig("fm_dist.png", dpi=150)
plt.show()

# =========================
# 8. 可视化 3：流场 v(x,t)
# =========================
# 对 1D 情况，流场是标量 v(x,t)，最直观的画法是:
#   横轴 t，纵轴 x，颜色表示速度大小
# 再叠加一些箭头
@torch.no_grad()
def eval_field(model, x_grid, t_grid):
    TT, XX = np.meshgrid(t_grid, x_grid)  # [Nx, Nt]
    x_in = torch.tensor(XX.reshape(-1, 1), dtype=torch.float32, device=device)
    t_in = torch.tensor(TT.reshape(-1, 1), dtype=torch.float32, device=device)
    v = model(x_in, t_in).reshape(len(x_grid), len(t_grid)).cpu().numpy()
    return TT, XX, v

x_grid = np.linspace(xmin, xmax, 140)
t_grid = np.linspace(0.0, 1.0, 41)
TT, XX, VV = eval_field(model, x_grid, t_grid)

plt.figure(figsize=(7, 5))
plt.imshow(
    VV,
    origin="lower",
    aspect="auto",
    extent=[t_grid.min(), t_grid.max(), x_grid.min(), x_grid.max()],
    cmap="coolwarm",
)
plt.colorbar(label="v(x,t)")

# 稀疏箭头：横向统一表示时间正方向，纵向表示速度
skip_x = slice(None, None, 8)
skip_t = slice(None, None, 4)
plt.quiver(
    TT[skip_x, skip_t],
    XX[skip_x, skip_t],
    np.ones_like(VV[skip_x, skip_t]),
    VV[skip_x, skip_t],
    angles="xy",
    scale_units="xy",
    scale=25,
    width=0.0025,
)

plt.xlabel("t")
plt.ylabel("x")
plt.title("Learned 1D Flow Field")
plt.tight_layout()
plt.savefig("fm_field.png", dpi=150)
plt.show()

# =========================
# 9. 可视化 4：若干粒子轨迹 x(t)
# =========================
probe_x0 = torch.linspace(-3.0, 3.0, 21, device=device).view(-1, 1)
ts_probe, traj_probe = euler_integrate(model, probe_x0, n_steps=100)
traj_probe = traj_probe[:, :, 0].cpu().numpy()  # [T+1, B]

plt.figure(figsize=(7, 5))
for i in range(traj_probe.shape[1]):
    plt.plot(ts_probe.cpu().numpy(), traj_probe[:, i], alpha=0.85)
plt.xlabel("t")
plt.ylabel("x(t)")
plt.title("Particle Trajectories Under Learned Flow")
plt.tight_layout()
plt.savefig("fm_traj.png", dpi=150)
plt.show()
